### ISSUE TITLE
Netlify is okay VPS is not

### ISSUE THREAD

**Issue by wiched** [davidbailey00/prettystyle#1]
I hope here is okay to write, i don't want to reopen the issue on gatsbyjs.

On Netlify the 404 is working, I created one for myself and I see it works.

On a VPN (apache) it does not work. Could that be .htaccess related?

This is my .htaccess
```
 RewriteEngine On
 RewriteBase /
 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteCond %{REQUEST_FILENAME} !-l
 RewriteRule ^.*$ / [L,QSA]
 Options -Indexes
```

**Comment by davidbailey00** [comment]
Your server is returning a 301 for /blog, which is causing the redirect:

![image](https://user-images.githubusercontent.com/4248177/45586793-5d33b180-b8f4-11e8-9533-b107544e3b02.png)

So this definitely isn't an issue with Gatsby :)

**Comment by davidbailey00** [comment]
I haven't used Apache much, so I can't help you out massively with this - but basically you need to make sure your server is handling 404s correctly.
